### ISSUE TITLE
Test expected return value 1 instead 0 

### ISSUE THREAD

**Issue by anais-f** [Ofacy/minishell-tester#23]
Several tests like that doesn't work very well les bebou !
Bash retourne 0 pas 1 ? Plus mon minishell me retourne 0 et non pas 255 ?! 

![Screenshot from 2024-06-05 13-43-57](https://github.com/Ofacy/minishell-tester/assets/116890624/5c2a2849-ab41-47b5-86de-b87d573f33ef)

**Comment by Ofacy** [comment]
The script **doesn't** create the _srcs_ folder, therefore **the redirection from the first command fails** and the file is not created.
Then bash returns 1 because **the file _srcs/bonjour_ does not exist** in the test environment during the second command's execution.

full bash output:
![image](https://github.com/Ofacy/minishell-tester/assets/63876319/5b39ae29-54bc-4f8c-8c20-94f75e7d1c4c)
